name: RAG Service CI/CD

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: ihebchaibi/rag-service

jobs:
  ci:
    name: Test application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Make Maven wrapper executable
        run: chmod +x mvnw

      - name: Run tests
        run: ./mvnw clean test

      - name: Build application
        run: ./mvnw package -DskipTests

  # Exécuté seulement avec un tag vX.Y.Z
  docker:
    name: Publish Docker image
    needs: ci

    if: startsWith(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Extract version
        id: version
        shell: bash
        run: |
          VERSION="${GITHUB_REF_NAME#v}"

          if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version: $VERSION"
            exit 1
          fi

          echo "value=$VERSION" >> "$GITHUB_OUTPUT"
          echo "Docker version: $VERSION"

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Verify version does not exist
        env:
          VERSION: ${{ steps.version.outputs.value }}
        run: |
          if docker manifest inspect "${IMAGE_NAME}:${VERSION}" > /dev/null 2>&1; then
            echo "Docker image ${IMAGE_NAME}:${VERSION} already exists."
            exit 1
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.value }}
            ${{ env.IMAGE_NAME }}:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max